name: Deploy SK3 to GitHub Pages

on:
  # Trigger the workflow every time you push and accept PR to the `main` branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Gets the code from the repo to be executed
      - name: Checkout
        uses: actions/checkout@v7

        # Install Node & PNPM and install dependencies in the same step
      - name: Setup pnpm with runtime
        uses: pnpm/setup@v3.0.0
        with:
          cache: true
          runtime: node@22

        # Sets basic configuration for paths and trailing slashs for sveltekit
      - name: Prepare project for github pages
        uses: actions/configure-pages@v6

        # Builds the application
      - name: Build
        run: pnpm run build

        #Prepares the files for deployment
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: "build/"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
